sudo: false
language: python
env:
  - PYTHON_VERSION=2.7
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq texlive
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export AG_TESTING='True'
  - export AG_CPU_COUNT=1
install:
  - conda create --yes -n env_name python=$PYTHON_VERSION --file conda_requirements.txt
  - source activate env_name
  - pip install -r pip_requirements.txt
  - pip install . --no-dep
script:
  - nosetests --with-doctest
  - flake8 americangut/*.py
  - flake8 scripts/*.py scripts/ag
  - ipymd --from markdown --to notebook ipynb/primary-processing/*.md
  - ./scripts/run_the_ipys.sh ipynb/primary-processing/
